import Link from "next/link";
import Image from "next/image";

export const metadata = {
  title: 'Propiedades',
  description: 'Generated by Next.js',
};

export default function Properties() {
  return (
    <section className="p-6">
      <h1 className="text-3xl font-bold underline mb-8 text-center">
        Propiedades en Alquiler
      </h1>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        {/* Tarjetas de propiedades */}
        {Array.from({ length: 8 }).map((_, index) => (
          <Link
            key={index}
            href={`/properties/${index + 1}`} // Enlace dinámico basado en propertiesId
            className="bg-white shadow-md rounded-lg overflow-hidden hover:shadow-lg transition-shadow"
          >
            <div>
              <Image
                src={`https://via.placeholder.com/300x200?text=Propiedad+${index + 1}`}
                alt={`Propiedad ${index + 1}`}
                className="w-full h-40 object-cover"
              />
              <div className="p-4">
                <h2 className="text-lg font-semibold mb-2">Propiedad {index + 1}</h2>
                <p className="text-gray-600">
                  Descripción breve de la propiedad {index + 1}. Ideal para alquiler.
                </p>
              </div>
            </div>
          </Link>
        ))}
      </div>
    </section>
  );
}