import Link from "next/link";
import "./_styles/globals.css";
export const metadata = {
  title: {
    default: "Rental Rosario",
    absolute: "",
    template: "%s | Rental Rosario",
  },
  description: "Generated by Next.js",
};

// src/app/layout.js

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head />
      <body>
        <header>
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              padding: "20px",
              backgroundColor: "#f8f9fa",
            }}
          >
            <div>
              <h1>Rental Rosario</h1>
              <p>Your one-stop solution for rental properties in Rosario.</p>
            </div>
          </div>
        </header>
        {children}
        <footer>
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              padding: "20px",
              backgroundColor: "#f8f9fa",
            }}
          >
            <div>
              <h4>About Us</h4>
              <p>Learn more about our company and mission.</p>
            </div>
            <div>
              <h4>Contact</h4>
              <p>Email: info@example.com</p>
              <p>Phone: +123 456 789</p>
            </div>
            <div>
              <h4>Follow Us</h4>
              <p>
                <a
                  href="https://facebook.com"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Facebook
                </a>
              </p>
              <p>
                <a
                  href="https://twitter.com"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Twitter
                </a>
              </p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
