import Footer from "./_components/molecules/Footer.jsx";
import "./_styles/globals.css";
export const metadata = {
  title: {
    default: "Rental Rosario",
    absolute: "",
    template: "%s | Rental Rosario",
  },
  description: "Generated by Next.js",
  icons: {
    icon: [
      {
        url: "/images/logo-rental-1.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any maskable",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head />
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
